{% set name = "leparagliding" %}
{% set version = "3.19" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.laboratoridenvol.com/leparagliding/leparagliding{{ version }}.f.zip
  sha256: b453d75b4594ed3097860521bf4d2090c4547b6f1d3f3bdf210ab2e108175655

build:
  number: 0

requirements:
  build:
    - {{ compiler("fortran") }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]

test:
  commands:
    - test -f ${PREFIX}/bin/leparagliding  # [unix]
    - test -f %LIBRARY_PREFIX%\bin\leparagliding.exe  # [win]

about:
  home: http://www.laboratoridenvol.com
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Advanced paragliding-design software written in fortran
  description: Advanced paragliding-design software written in fortran
  doc_url: http://www.laboratoridenvol.com/leparagliding
  dev_url: http://www.laboratoridenvol.com/leparagliding

extra:
  recipe-maintainers:
    - looooo
