{% set name = "leparagliding" %}
{% set version = "3.18" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.laboratoridenvol.com/leparagliding/leparagliding{{ version }}.f.zip
  sha256: a4779c997cb6b183672258f4c54cb6faab6e7c12fe24af4892032c8397e5e577

build:
  number: 0

requirements:
  build:
    - {{ compiler("fortran") }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]

test:
  commands:
    - test -f ${PREFIX}/bin/leparagliding  # [unix]
    - test -f %LIBRARY_PREFIX%\bin\leparagliding.exe  # [win]

about:
  home: http://www.laboratoridenvol.com
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Advanced paragliding-design software written in fortran
  description: Advanced paragliding-design software written in fortran
  doc_url: http://www.laboratoridenvol.com/leparagliding
  dev_url: http://www.laboratoridenvol.com/leparagliding

extra:
  recipe-maintainers:
    - looooo
