{% set name = "leparagliding" %}
{% set version = "3.20" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.laboratoridenvol.com/leparagliding/leparagliding{{ version }}.f.zip
  sha256: 2810686eedc5273da237a81ec80a9178924cab437312688a6d033aa7fa887bc7

build:
  number: 1

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("fortran") }}

test:
  commands:
    - test -f ${PREFIX}/bin/leparagliding  # [unix]
    - test -f %LIBRARY_PREFIX%\bin\leparagliding.exe  # [win]

about:
  home: http://www.laboratoridenvol.com
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Advanced paragliding-design software written in fortran
  description: Advanced paragliding-design software written in fortran
  doc_url: http://www.laboratoridenvol.com/leparagliding
  dev_url: http://www.laboratoridenvol.com/leparagliding

extra:
  recipe-maintainers:
    - looooo
