context:
  name: leparagliding
  version: 3.25

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: http://www.laboratoridenvol.com/leparagliding/leparagliding${{ version }}.f.zip
    sha256: 4b671be22f99ca3158513da11d37aa6e6a4ddc750c17594d40dec3d4f876bf97

build:
  number: 0

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("fortran") }}
    - ${{ stdlib("c") }}

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/bin/leparagliding

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Advanced paragliding-design software written in fortran
  description: Advanced paragliding-design software written in fortran
  homepage: http://www.laboratoridenvol.com
  repository: http://www.laboratoridenvol.com/leparagliding
  documentation: http://www.laboratoridenvol.com/leparagliding

extra:
  recipe-maintainers:
    - looooo
